### ISSUE TITLE
找不到ambry_sources

### ISSUE THREAD

**Issue by jiadengyuan** [CivicKnowledge/public-search#4]
Installed /usr/local/virtualenv/lib/python3.6/site-packages/ambry-0.3.2066-py3.6.egg
Processing dependencies for ambry==0.3.2066
Searching for ambry_sources
Reading https://pypi.org/simple/ambry_sources/
Reading https://pypi.org/simple/ambry-sources/
Couldn't find index page for 'ambry_sources' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for ambry_sources
error: Could not find suitable distribution for Requirement.parse('ambry_sources')

**Comment by ericbusboom** [comment]
Hi jiadengyuan, this organization is a graveyard for old, dead projects; I should probably turn off public access, ( Sorry!)  If you are interested in a data package manager, see [Metatab](http://metatab.org),
